# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
pod "AFNetworking"
pod "SVPullToRefresh"
pod 'Venmo-iOS-SDK'

target 'PPV12' do

end

target 'PPV12Tests' do

end

